# Generated by Codex on 2026-07-05

import system_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_settings", "0002_systemsettings_time_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="app_lock_enabled",
            field=models.BooleanField(
                "Require sign-in and enable lock screen",
                default=False,
                help_text="Opt in to sign-in and the manual lock screen for this local app.",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="login_lockout_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Opt in to temporary lockouts after repeated failed sign-in attempts.",
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="lock_shortcut_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Allow Ctrl+Shift+L to lock the desktop app when the lock screen is enabled.",
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="time_zone",
            field=models.CharField(
                default=system_settings.models.default_time_zone,
                help_text="Used to display exact times, such as encounters, observations, and imports.",
                max_length=64,
            ),
        ),
    ]
